import { ResearchCampaign } from './types';

// Rate: 1 SOL ≈ 175 USD
export const SOL_USD_RATE = 175;

export const INITIAL_CAMPAIGNS: ResearchCampaign[] = [
  {
    id: 'bounty-glioblastoma-01',
    title: 'Таргетная терапия мультиформной глиобластомы нанокапсулами через преодоление ГЭБ',
    medicalProblem: 'Глиобластома (агрессивная опухоль мозга)',
    unresolvedBarrier: 'Гематоэнцефалический барьер (ГЭБ) блокирует 98% существующих хемопрепаратов, обрекая пациентов на медианную выживаемость всего 14 месяцев.',
    proposedSolution: 'Синтез биомиметических липосомальных наночастиц с пептидными лигандами LRP1 для трансцитоза через сосудистый барьер и точечной доставки ингибиторов сигнальных путей напрямую в клетки глиобластомы.',
    category: 'oncology',
    scientist: {
      id: 'sci-elena-voronova',
      name: 'Д-р Елена Воронова',
      title: 'Кандидат биологических наук, старший научный сотрудник',
      institution: 'Институт биомедицинских нанотехнологий',
      orcid: '0000-0002-8419-4211',
      avatarUrl: '/images/dr_elena_neuro_1791372939892.jpg',
      solanaAddress: '6LYvu5NNPf2Mv8VAq24f5QoN7FuDqA31J7JFSW2Y5B1y',
    },
    targetAmount: 85000,
    raisedAmount: 54250,
    targetSol: 485.7,
    raisedSol: 310.0,
    donorCount: 142,
    daysRemaining: 19,
    stage: 'Доклинические испытания in vitro на срезах ткани',
    budgetBreakdown: [
      { item: 'Реактивы для синтеза липидных матриц', percentage: 40, amount: 34000, amountSol: 194.2 },
      { item: 'Аренда конфокального флуоресцентного микроскопа', percentage: 30, amount: 25500, amountSol: 145.7 },
      { item: 'Первичные клеточные культуры глиобластомы человека', percentage: 20, amount: 17000, amountSol: 97.1 },
      { item: 'Оплата работы аспирантов-биохимиков', percentage: 10, amount: 8500, amountSol: 48.5 },
    ],
    recentDonations: [
      { id: 'tx-1', donorName: 'Фонд поддержки нейронаук', amountSol: 28.5, amountUsd: 5000, timestamp: '2 часа назад', message: 'Критически важное направление для нейроонкологии!', signature: '5hK8...9pX2' },
      { id: 'tx-2', donorName: 'Solana Devnet DAO', amountSol: 2.85, amountUsd: 500, timestamp: '5 часов назад', message: 'В память о друге. Удачи вашей лаборатории.', signature: '3mY4...7aL1' },
      { id: 'tx-3', donorName: 'BioHealth Ventures', amountSol: 14.28, amountUsd: 2500, timestamp: '1 день назад', message: 'Надеемся на скорый переход к фазе in vivo.', signature: '8rT9...2kQ5' },
    ],
  },
  {
    id: 'bounty-tnbc-car-t-02',
    title: 'Репрограммирование T-клеток для ликвидации микрометастазов трижды негативного рака груди',
    medicalProblem: 'Трижды негативный рак молочной железы (ТНРМЖ)',
    unresolvedBarrier: 'Отсутствие рецепторов HER2, ER и PR делает стандартную гормональную и таргетную терапию бесполезной. Быстрое метастазирование в легкие и кости.',
    proposedSolution: 'Конструирование CAR-T клеток 4-го поколения с локальной секрецией интерлейкина-18 для преодоления иммуносупрессивного микроокружения стромы опухоли.',
    category: 'oncology',
    scientist: {
      id: 'sci-marcus-levin',
      name: 'Д-р Маркус Левин',
      title: 'PhD в области онкоиммунологии',
      institution: 'Лаборатория адаптивной клеточной иммунотерапии',
      orcid: '0000-0001-9230-5847',
      avatarUrl: '/images/dr_marcus_onco_1791372957402.jpg',
      solanaAddress: 'HMpQbLXWZS37CJK4CTPhiwSrpCiPumu2MTN3kHJferq5',
    },
    targetAmount: 120000,
    raisedAmount: 91525,
    targetSol: 685.7,
    raisedSol: 523.0,
    donorCount: 318,
    daysRemaining: 12,
    stage: 'Векторная трансдукция и цитометрическая валидация',
    budgetBreakdown: [
      { item: 'Синтез лентивирусных векторов с IL-18', percentage: 45, amount: 54000, amountSol: 308.5 },
      { item: 'Проточная мультипараметрическая цитометрия', percentage: 25, amount: 30000, amountSol: 171.4 },
      { item: 'Изоляция донорских мононуклеаров (PBMC)', percentage: 20, amount: 24000, amountSol: 137.1 },
      { item: 'Сертификация клеточных партий', percentage: 10, amount: 12000, amountSol: 68.5 },
    ],
    recentDonations: [
      { id: 'tx-4', donorName: 'Семейный фонд Ковалевых', amountSol: 57.1, amountUsd: 10000, timestamp: '3 часа назад', message: 'Верим в прорыв вашей команды!', signature: '9pL3...4kM8' },
      { id: 'tx-5', donorName: 'OncoHope Community', amountSol: 6.85, amountUsd: 1200, timestamp: '1 день назад', signature: '2wX7...8bN4' },
    ],
  },
  {
    id: 'bounty-als-prime-editing-03',
    title: 'Prime Editing и эпигенетическое подавление патологических экспансий при БАС',
    medicalProblem: 'Боковой амиотрофический склероз (БАС / болезнь Шарко)',
    unresolvedBarrier: 'Каскадная гибель мотонейронов спинного мозга необратима; коммерческая фарма ограничивается препаратами, продлевающими жизнь всего на 2-3 месяца.',
    proposedSolution: 'Применение высокоточного редактора оснований Prime Editor для исправления гексануклеотидных повторов GGGGCC в гене C9orf72 без двунитевых разрывов ДНК.',
    category: 'neurology',
    scientist: {
      id: 'sci-anya-gromova',
      name: 'Д-р Анна Громова',
      title: 'Кандидат медицинских наук, генетик-исследователь',
      institution: 'Центр прецизионного редактирования генома',
      orcid: '0000-0003-1120-7794',
      avatarUrl: '/images/dr_anya_genetics_1791372971118.jpg',
      solanaAddress: '9n2P8e4ftZue25jqr5UGYyueztBovASdmpj8d4LTN7mu',
    },
    targetAmount: 95000,
    raisedAmount: 38500,
    targetSol: 542.8,
    raisedSol: 220.0,
    donorCount: 94,
    daysRemaining: 27,
    stage: 'Дизайн спейсерных guide RNA и оценка off-target эффектов',
    budgetBreakdown: [
      { item: 'Высокопроизводительное таргетное NGS-секвенирование', percentage: 40, amount: 38000, amountSol: 217.1 },
      { item: 'Индуцированные плюрипотентные стволовые клетки (iPSC)', percentage: 35, amount: 33250, amountSol: 190.0 },
      { item: 'Аденоассоциированные векторы доставки AAV9', percentage: 25, amount: 23750, amountSol: 135.7 },
    ],
    recentDonations: [
      { id: 'tx-6', donorName: 'Альянс исследователей мотонейронов', amountSol: 17.14, amountUsd: 3000, timestamp: '4 часа назад', message: 'БАС должен быть побежден!', signature: '6zQ1...9vC3' },
      { id: 'tx-7', donorName: 'Phantom User', amountSol: 1.42, amountUsd: 250, timestamp: '6 часов назад', signature: '4kT5...1mY8' },
    ],
  },
  {
    id: 'bounty-superbugs-phage-04',
    title: 'Синтетические бактериофаги против панрезистентных госпитальных штаммов Klebsiella pneumoniae',
    medicalProblem: 'Панрезистентные суперинфекции (NDM-1 & KPC)',
    unresolvedBarrier: 'Крупные фармкомпании свернули программы разработки антибиотиков из-за низкой финансовой отдачи. Пациенты в реанимациях погибают от бактерий, устойчивых ко всем известным препаратам.',
    proposedSolution: 'Биоинженерная сборка персонализированных поливалентных фаговых коктейлей с эндолизинами, расщепляющими биопленку микроорганизмов за 40 минут.',
    category: 'infectious',
    scientist: {
      id: 'sci-viktor-soloviev',
      name: 'Проф. Виктор Соловьев',
      title: 'Доктор медицинских наук, профессор микробиологии',
      institution: 'Консорциум по преодолению антимикробной резистентности',
      orcid: '0000-0002-3901-4432',
      avatarUrl: '',
      solanaAddress: 'Qm6pWMxnJMDHZHZodWDRUMEpatRghkmPSJPviuqmCT5',
    },
    targetAmount: 60000,
    raisedAmount: 47775,
    targetSol: 342.8,
    raisedSol: 273.0,
    donorCount: 215,
    daysRemaining: 8,
    stage: 'Селекция фаговых изолятов и картирование спектра лизиса',
    budgetBreakdown: [
      { item: 'Оборудование для хроматографической очистки эндолизинов', percentage: 45, amount: 27000, amountSol: 154.2 },
      { item: 'Тестирование на клинических изолятах ОРИТ', percentage: 35, amount: 21000, amountSol: 120.0 },
      { item: 'Расходные материалы и питательные среды', percentage: 20, amount: 12000, amountSol: 68.5 },
    ],
    recentDonations: [
      { id: 'tx-8', donorName: 'Ассоциация врачей интенсивной терапии', amountSol: 25.7, amountUsd: 4500, timestamp: 'Вчера', message: 'Ждем эти фаги в клинической практике!', signature: '1bN7...8kL4' },
    ],
  },
  {
    id: 'bounty-fibrosis-crispr-05',
    title: 'Ингибирование миофибробластной трансдифференцировки при идиопатическом фиброзе легких',
    medicalProblem: 'Идиопатический фиброз легких (ИФЛ)',
    unresolvedBarrier: 'Прогрессирующее рубцевание легочной ткани необратимо снижает жизненную емкость легких. Существующие ингибиторы киназ лишь замедляют угасание дыхания.',
    proposedSolution: 'Эпигенетическое подавление транскрипционного фактора SMAD3 с помощью микроРНК-нанокомплексов для остановки фиброгенеза и запуска эндогенного ремоделирования альвеол.',
    category: 'rare_diseases',
    scientist: {
      id: 'sci-timur-khasanov',
      name: 'Д-р Тимур Хасанов',
      title: 'Кандидат биологических наук, пульмонолог-исследователь',
      institution: 'Институт регенеративной пульмонологии',
      orcid: '0000-0002-7714-9031',
      avatarUrl: '',
      solanaAddress: '4Rrwd3jdguSRUvetvgkNyMbnGD1sRrPTRp6TW7MaRHjy',
    },
    targetAmount: 70000,
    raisedAmount: 29400,
    targetSol: 400.0,
    raisedSol: 168.0,
    donorCount: 88,
    daysRemaining: 34,
    stage: 'Оценка аэрозольной доставки в альвеолярные компартменты',
    budgetBreakdown: [
      { item: 'Генератор аэрозольных наносуспензий для ингаляций', percentage: 40, amount: 28000, amountSol: 160.0 },
      { item: 'Гистохимические маркеры коллагенолиза', percentage: 35, amount: 24500, amountSol: 140.0 },
      { item: 'Биобанкирование легочных эксплантатов', percentage: 25, amount: 17500, amountSol: 100.0 },
    ],
    recentDonations: [
      { id: 'tx-9', donorName: 'Частный донор (Phantom)', amountSol: 8.57, amountUsd: 1500, timestamp: '1 день назад', signature: '7xM9...3bV2' },
    ],
  },
];

export const CATEGORY_LABELS: Record<string, string> = {
  all: 'Все сборы',
  oncology: 'Онкология',
  neurology: 'Неврология & Нейродегенерация',
  genetics: 'Генетические патологии',
  infectious: 'Суперинфекции & Резистентность',
  rare_diseases: 'Редкие заболевания',
};

export const INITIAL_BLOCKCHAIN_RECORDS = [
  {
    id: 'tx-memo-init-1',
    text: 'AI Medical Research Bounty: Фиксация грантовой поддержки исследования глиобластомы (Д-р Воронова)',
    timestamp: '07.10.2026, 11:42',
    txSignature: '5hK8vQf2zU3T7vP3y9NZmcEw8G52zs189NSZ18LN2kQ5j',
    explorerUrl: 'https://explorer.solana.com/tx/5hK8vQf2zU3T7vP3y9NZmcEw8G52zs189NSZ18LN2kQ5j?cluster=devnet',
  },
  {
    id: 'tx-memo-init-2',
    text: 'AI Medical Research Bounty: Регистрация лабораторного протокола CAR-T терапии ТНРМЖ (Д-р Левин)',
    timestamp: '07.10.2026, 09:15',
    txSignature: '3mY4b8a3p3m3jFpG9fT8q4fE3vL1pA5dG8hC2sW97aL1k',
    explorerUrl: 'https://explorer.solana.com/tx/3mY4b8a3p3m3jFpG9fT8q4fE3vL1pA5dG8hC2sW97aL1k?cluster=devnet',
  },
];
